### ISSUE TITLE
Questions for Fall 2018

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/Fluoride_Gravity#9]
1. Balance reading, inconsistence measurement intervals
2. "Explore options for taking this technology to the field. Begin this exploration right away at the beginning of the semester."
3. When starting flow through system, we have to take down the reactor to get enough head to start the system. Is there a better way to do this? 
4. Herrboldt thesis: natural organic matter and fluoride; aluminum sulfate, binding affinity as pH changes, comparison to PACl 
5. Flow rate out of coagulant stock does not always equal the flow rate out of the coagulant constant head tank (same with fluoride). How can we account for this in order to measure the flow rate of coagulant into the system? 
6. Fluoride Auto team assumed steady state at 1.5 hours, created isotherm based on readings taken at only 1.5 hrs. 
7. Turbidity - is this a parameter we should be concerned about? Could be useful in determining optimal upflow velocity - adjust velocity until we get to a point where we see flocs. 
8. Flocs? What should flocs look like vs. gel? 
9. pH & temperature might affect fluoride readings? variability between samples during an experiment

**Comment by cheertsang** [comment]
"optimal pH for aluminum coagulant nanoparticle formation is between pH of 6.5 and 8.5"
([AguaClara textbook](https://aguaclara.github.io/Textbook/Rapid_Mix/RM_Intro.html))
- same as [EPA secondary standards for drinking water](https://www.epa.gov/dwstandardsregulations/secondary-drinking-water-standards-guidance-nuisance-chemicals)

PACl is less mass, more cost-effective, consumes less alkalinity than alum (aluminum sulfate) (AguaClara textbook)

"velocity gradient is independent of viscosity (and hence temperature) for laminar flow. This is because the total amount of fluid deformation is simply based on geometry" (AguaClara textbook)

"Dissolved organic matter may slow the rate of coagulant nanoparticle transport by effectively increasing the size of the coagulant nanoparticles and thus reducing the diffusion rate" [(AguaClara textbook)](https://aguaclara.github.io/Textbook/Rapid_Mix/RM_Theory_and_Future_Work.html)

"As turbidity increases the spacing between clay particles decreases and the time required for shear to transport coagulant nanoparticles to the clay decreases."
- "Increasing the shear also results in faster transport of the coagulant nanoparticles to clay surfaces. The times required are strongly influenced by the size of the coagulant nanoparticles because larger nanoparticles diffuse more slowly."

**Comment by cheertsang** [comment]
Dehalococcoides - bacteria that reduced halogen compounds? maybe do some research on this, see how useful it could be in breaking down concentrated fluoride waste
